Add support for manual file locking
owncloud/files_texteditor pull request #337
Opened 2021-01-22 11:19 UTC by JammingBen

OC 10.5 introduced manual file locking. This change adds the functionality to the files texteditor app. How it basically works: User 1 shares a file with User 2, then locks it. Now User 2 is still able to view this file, but editing is not possible and will result in the message "The file is locked" (similar to when it has been locked via transactional locking).

![image](https://user-images.githubusercontent.com/50302941/105484372-7eb6bc00-5cab-11eb-8742-ff77cbcce23f.png)

2021-01-22 20:35 UTC, DeepDiver1975 requested changes
see commment ...


in addition: A much cleaner approach would be to drop the filehandling controller and use webdav directly.
then there is no need in adding locking support because it is part of the webdav protocol ... just saying

2021-01-22 20:35 UTC, DeepDiver1975 commented on controller/filehandlingcontroller.php
> +						$lookingEnabled = $this->config->getAppValue("files", "enable_lock_file_action", "no") === "yes";
you should check for lock even if the app setting is disbled.
the app config only controlls if the front end for locking is enabled.

files can be locked even if the config is off

2021-01-25 08:19 UTC, JammingBen commented
@DeepDiver1975 

> in addition: A much cleaner approach would be to drop the filehandling controller and use webdav directly.
then there is no need in adding locking support because it is part of the webdav protocol ... just saying

Do you have an example of such implementation? Although it sounds like it would need some deeper refactoring... Maybe something to keep in mind for the future, but not for this PR?

2021-03-05 10:51 UTC, jnweiger commented
@JammingBen @DeepDiver1975 
Can you update and finish this PR? 
Apart fom this, we are ready for a 2.3.1 release of files_texteditor.

2021-05-20 11:32 UTC, phil-davis commented
@JammingBen is this still a thing?
It is stck on my GitHub review requests list.

2021-05-28 09:41 UTC, JammingBen commented
Feature-wise I still think it's useful. But I'm not quite sure about the implementation. Maybe @jvillafanez or @mrow4a can have a look?

Anyway, I wouldn't spent too much effort on this as it was not "officially" requested. So if we would need to look for another way to implement, I would rather close this for now.

2021-05-31 07:08 UTC, jvillafanez commented
I'd keep it frozen for now. There are a couple of things to be checked with the approach:
* If you need to check whether the storage is a locking storage or not, it doesn't look good. A controller shouldn't worry about that.
* Main operations for the locking storage are "lock" and "unlock". The "getLocks" is there to provide a better knowledge for the "lock" and "unlock" operations, but I don't think the intention is to use it on its own.

I think the code itself is fine, so we can keep it in case we need a fast response if someone requests it.

2021-05-31 10:06 UTC, JammingBen commented
Ok, I'm closing this for now. We can still reopen it once needed.

2021-05-31 10:06 UTC, closed without merging